### ISSUE TITLE
Incorrect rendering of calendar when navigate fast

### ISSUE THREAD

**Issue by webartistse** [krystalcampioni/vue-hotel-datepicker#100] opened 2018-10-22 08:30 UTC
If the user navigate fast and mix up with clicking next/previous the calendar is starting to render months in wrong order or render duplicates. This is quite easy to reproduce in Chrome on Mac and Win.

![screenshot 2018-10-22 at 10 27 38](https://user-images.githubusercontent.com/3966652/47283884-6c89d700-d5e5-11e8-9113-4f5f3069ae18.png)
![screenshot 2018-10-22 at 10 27 54](https://user-images.githubusercontent.com/3966652/47283888-6dbb0400-d5e5-11e8-816c-f4dfec3c3c6d.png)

**Comment by krystalcampioni** [comment] 2018-10-24 20:14
Duplicate of #101

**Closed by krystalcampioni** 2018-10-24 20:14 UTC
